apiVersion: v1
kind: Service
metadata:
  name: lbservice
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: awsmentapp
  type: LoadBalancer
